### ISSUE TITLE
missing colorama dep

### ISSUE THREAD

**Issue by karchern** [afombravo/tnseeker#2]
Hey Afonso,

Tnseeker runs for me but the most recent commit lacks the `colorama` dependency. So I need to additionally do `pip install colorama` (after `pip install git+https://github.com/afombravo/tnseeker.git@fa146e353e8f00f6965956e55c895f398c3ed458`) to make it run through.

Just FYI if you want to update `setup.py`

Cheers,
Nic

**Comment by afombravo** [comment]
yeah for some reason the PyPI version is ahead of my git one (probably lazyness). if you do pip install fast2q its working there already with that added.
