### ISSUE TITLE
Migrate barcode2sam.sh to python code

### ISSUE THREAD

**Issue by karchern** [afombravo/tnseeker#4]
In my hands, when building the container from the git repo code using `docker build`, the container is not functional as I get permission issues for the `barcode2sam.sh` script.

Suggestion: Migrate to python code and fold it into the package this way.

**Comment by afombravo** [comment]
For now, if you want to build from souce I would recommend giving chmod +x permissions to that file beforehand. Alternatively you can just download the working image from dockerhub as mentioned in the README.

I will leave the issue open until a refactor is performed

**Comment by afombravo** [comment]
Fixed.
